version: "3.9"
services:
  postgres:
    image: postgres:15  # Use the latest stable PostgreSQL image
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passowrd001
      POSTGRES_DB: oriontek-clients
    ports:
      - "5435:5432"  # Map the container's port 5432 to your host's port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data  # Mount a named volume for persistent storage

volumes:
  pgdata:
